### PR TITLE
Cleaned up README

### PR DESCRIPTION
**Pull request by midischwarz12**

### CODE REVIEW

**Comment by midischwarz12** [comment]
Oh, you have two different make files. You should have those as one with a different make routine. Hmm, I'll put some work on this in a bit.

**Comment by midischwarz12** [comment]
It would be nice to have a `make example` and `make install` commands.

**Comment by midischwarz12** [comment]
@RealAlpha Any thoughts?

**Comment by lthoma5** [comment]
Great changes! As you said in your comment, the two make files are indeed for separate things (one is for the library and one is for the example).

Other than that, I'd argue that clang may not be a _direct_ dependency of Discord-C: sure, it's used, but it isn't linking against it or using any clang-specific stuff. I'm still playing around with CMake to try to get it to build that way, which should add support for virtually any C/C++ compiler (including say `gcc` and maybe `MSVC`). Unfortunately it's been a while since I last used CMake, so it might take a while before I manage to finish the transition. In the mean time I'll leave this point to your discretion, so if you can clarify the two make _steps_ I can merge it.

----

Finally, for your other comment: I can definitely see the advantages to that. I'll likely use CMake for that once I finish it, but if you feel like it would be advantageous to include it in the Makefile until then, then feel free to submit a (separate) PR for that

**Pull request closed without merging**
